"""add likes table

Revision ID: 28abfefbfe80
Revises: 3b7a2c30b42a
Create Date: 2025-12-15 00:55:59.727282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28abfefbfe80'
down_revision = '3b7a2c30b42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
